### ISSUE TITLE
Copied content.

### ISSUE THREAD

**Issue by m-spangenberg** [TheKidPadra/CS50P#1]
What exactly are you trying to achieve by copying [my work](https://github.com/m-spangenberg/CS50P)? 

Using the contents of my repository and presenting them as your own is dishonest. I suggest you do your own work.

**Comment by TheKidPadra** [comment]
Hello dear m-spangenberg,
I checked as soon as I could, I ask one of my friend to create the README.md file for the repo because I'm not the only one has access to this account, and apparently he copied part of your README.md file and I delete it. I'm so sorry for the inconvenient .but I checked everything else and I can assure you nothing else is similar because it's my own code.
Again, I'm so sorry 
thank you for your understanding.

**Comment by m-spangenberg** [comment]
Ah, a 'friend'. I see.

All your own work, you say?

Like this identical file?

- [My PSET7 response.py](https://github.com/m-spangenberg/CS50P/blob/0b799082a415361744fe6a57f4003ba926fa37ab/pset7/response/response.py)
- [Your PSET7 response.py](https://github.com/TheKidPadra/CS50P/blob/871723beacdf58b6682dad5f1731ac17b377e06e/Problem%20Set%207/response/response.py)

And this identical file?

- [My PSET7 working.py](https://github.com/m-spangenberg/CS50P/blob/0b799082a415361744fe6a57f4003ba926fa37ab/pset7/working/working.py)
- [Your PSET7 working.py](https://github.com/TheKidPadra/CS50P/blob/871723beacdf58b6682dad5f1731ac17b377e06e/Problem%20Set%207/working/working.py)

Or this identical file?

- [My PSET7 test_working.py](https://github.com/m-spangenberg/CS50P/blob/0b799082a415361744fe6a57f4003ba926fa37ab/pset7/working/test_working.py)
- [Your PSET7 test_working.py](https://github.com/TheKidPadra/CS50P/blob/871723beacdf58b6682dad5f1731ac17b377e06e/Problem%20Set%207/working/test_working.py)

And those are only the files I cared to look for. Your 'friend' has been working _very_ hard.

I forgive your 'friend', life is hard and we are always tempted to find easy solutions to hard problems.
